name: Run Backend Radicale Tests

on:
  workflow_dispatch:

jobs:
  radicale-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: ./.github/actions/setup-java-maven

      - name: Run Radicale Docker Tests
        run: mvn clean test -B -Dtest=RadicaleComposeTest
